vazio: ENC[AES256_GCM,data:e5HqWQ==,iv:/locc8pd8s/1Px1Kdu5Uyu8FznO41GHwe0UnKIx5QZQ=,tag:AeAO0JWqDGFoBYBsL5vA4w==,type:bool]
sops:
    age:
        - recipient: age1hvamwn0k7ucvscqnnju6nz4l4f2w4h8f3alrwcd6ammyt4funujqy5k0gy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNXhMeGxGNnZKaXZoM1BS
            NXM5YnE2UjF5MnRlV24yaUNPSXBNc2lYUFJrCjVXSm5yTU9na1lHVXgybGZGeWJS
            dER0U0JqeUQvMFVURGNsZTdtV0RDUWMKLS0tIFo5aERiamdteFVnQ29PMFdxa1hY
            bXUwREtmNUt6emlPZ0hUUEpNcUdGSVkK8HbD2paFORVSO4f96dPrELI70Y4Uy4p1
            OkxWT8YJe3zUnZxPiuyQ4WTD0gs/kITiM2w+7au+0ri3Xw4IP8Ua+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T19:53:22Z"
    mac: ENC[AES256_GCM,data:Xl5GQ3/Dk9JNUDoycakd21dPbaoAGBIVx86XKTcZQhQOAyuuYT70/aQsl8eRxRZcpli4FZBHZxkQkDDqgsA1BSITIYtA3KjiJpYEzx/bxsoFau/Z0T+ac05g0R73xPpVIlb8RLDJAsORsgz4d1GzXlDNm5SAaWwYiwDe/H7Frdc=,iv:Xo1QaTT2B1YzuUYkb1qSrl0V62G9fRc8Q69lpfVk7/M=,tag:5jjJykecfFglgj/8/3MJcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
