environment: production

fqdn: sgea.digital

extraRouteLabels:
    intranet: 'true'
env:
    apiUrl: https://sgea.digital/api
    baseUrl: https://sgea.digital/
    production: 'true'
    ambiente: 'production'
    useSimpleAuth: 'true'

resources:
    limits:
        cpu: 512Mi
        memory: 1Gi
    requests:
        cpu: 256Mi
        memory: 512Mi
