{{- if .Values.image.credentials }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "escala-agro-web.fullname" . }}-image-pull-credentials
  labels:
    {{- include "escala-agro-web.labels" . | nindent 4 }}
stringData:
  .dockerconfigjson: {{ template "escala-agro-web.imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}
